version: '2'
services:

  app:
    build: ./app
    expose:
      - "3000"

  nginx:
    image: "nginx:1.13.10"
    ports:
     - "80:8080"
    volumes:
     - ./proxy/conf.d:/etc/nginx/conf.d
    depends_on:
     - app