branch-defaults:
  master:
    environment: null
global:
  application_name: myweb
  branch: null
  default_ec2_keyname: sanghee
  default_platform: 64bit Amazon Linux 2017.03 v2.7.1 running Multi-container Docker 17.03.1-ce (Generic)
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
