FROM thehackerati/node-app-template

# Install development and debugging tools
RUN npm install nodemon -g && \
    npm install grunt-cli -g

# Use changes to package.json to force Docker not to use the cache
# when we change our application's nodejs dependencies:
ADD package.json /tmp/app/package.json
RUN cd /tmp/app && npm install

WORKDIR /opt/app

# Run CMD from the default ENTRYPOINT: /bin/sh -c /opt/app/run-dev-mode.sh
CMD ["/opt/app/run-dev-mode.sh"]